name: MPh # This will become the name of your environment
dependencies: # The list of packages to include in your environment
    - python=3.12 # You can specify versions
    - pip # Install pip in your environment
    - tqdm 
    - ipykernel 
    - pyyaml
    - pip: # Include pip dependencies last
        - MPh